### ISSUE TITLE
advanced filter on bank/cash accounts

### ISSUE THREAD

**Issue by Ton558** [moneymanagerex/moneymanagerex#2631]
hi,
the function advanced filter on bank/cash accounts no longer filters.

![image](https://user-images.githubusercontent.com/63596191/85252953-618fe580-b45d-11ea-9f4b-3e05de3089b9.png)

regards,

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [x] 1.3.5
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by vomikan** [comment]
Hi. What exactly does not working?

It's working for me on Bank account 
![image](https://user-images.githubusercontent.com/6836805/85259093-197abe00-b471-11ea-86c5-fe0af2336baf.png)

**Comment by dl200010** [comment]
I just updated to 1.3.5 and tried to filter by "All Except Reconciled", and it doesn't filter. I tried "Un-Reconciled", and it doesn't filter. The "Displayed Bal" seems to update, but don't know if it is proper. The list of transactions just don't change.

**Comment by vomikan** [comment]
@dl200010 

I can't reproduce this issue
![image](https://user-images.githubusercontent.com/6836805/85414856-4dd7a280-b575-11ea-9fa1-0382102993b7.png)

**Comment by dl200010** [comment]
![image](https://user-images.githubusercontent.com/1350201/85422279-0d5b3300-b53b-11ea-9bff-c3a193d4f223.png)

![image](https://user-images.githubusercontent.com/1350201/85422320-164c0480-b53b-11ea-885f-e30f22f30998.png)

**Comment by GuitarMan63** [comment]
Hi I've updated to version 1.35 this morning and have the very same issue. The advanced filter does not work, no matter whether I select specific categories , or whether transactions are reconciled or not. I frequently use this feature to filter and reconcile my accounts. I'm using Windows 10 64 bit on the latest build. Other than that as ever it's a great peice of software, Thanks

**Comment by vomikan** [comment]
![image](https://user-images.githubusercontent.com/6836805/85429650-b465bc00-b587-11ea-8970-8d162388e83d.png)

**Comment by dl200010** [comment]
@vomikan What are you trying to show?

**Comment by vomikan** [comment]
It's working for me.
I don't know what exactly should be fixed.

**Comment by dl200010** [comment]
@vomikan Try downloading the installer on the site and use that.

**Comment by vomikan** [comment]
Result the same working for me

Money Manager Ex
Version: 1.3.5
• Database version: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.3 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/7.59.0-DEV WinSSL
Build on Jun 17 2020 10:30:46 with:
• CMake 3.16.2
• MSBuild 15.9.21.664
• gettext 0.19.8.1
• Microsoft Visual Studio 15.0
• Microsoft Visual C++ 19.16.27035.0
• Windows SDK 10.0.14393.0
Running on:
• Windows 10 (build 18363), 64-bit edition
• (windows-1251)
• 1920x1080 32bit 96x96ppi

**Comment by dl200010** [comment]
@vomikan I will try the portable, but I am using the installed one.

**Comment by dl200010** [comment]
@vomikan I still have the same issue on portable. Maybe it has to do with the number of accounts (3) I have and the number of entries (11528) I have. There is an issue where where it does not update the spreadsheet like section when trying to filter. It does now seem to keep the last filter setting, but when the program boots up it still is not filtered.

**Comment by GuitarMan63** [comment]
@vomikan Thanks for the guidance, I've just downloaded the Windows 64 bit from this site and reinstalled, the result is the same. I've also tried the portable version, still the same. With version 1.34 I could apply filters to show, reconciled or none and it worked perfectly, with 1.35 if I select the same or if I select a specific transaction nothing changes, no filter whatsover. I'm using the database in encrypted format and have a over 25 accounts tracked. I will try instaling the Linux version on my other PC to see if that is any different and give an update. Thanks

**Comment by GuitarMan63** [comment]
@vomikan Figured out what is happening, there is a disk icon and if I click that first then go OK the filter works, there was either no disk icon on 1.34 or you could just select OK when using the filters, or at least as far as I know. Thanks

**Comment by vomikan** [comment]
You can save 9 pre-settings then use it for your convinience.

**Comment by GuitarMan63** [comment]
@vomikan Thanks for that, the filter still does not seem to work quite as I'd have expected. For example I've set two advanced filters on one of my accounts one using none and the other reconciled, I've saved these as 0 &1 on the preset. I go into the account and select the advanced filter and apply preset 0 and hit Ok the filter is applied. I then try the second filter which is allocated against 1, select OK and nothing changes the transaction stays filtered on none, rather than switching to reconciled. I have to untick the selected account apply clear, then select the preset again save and then go OK to apply the filter. I would have thought I could simply move between the presets and the changes would apply with just an OK selection.

**Comment by vomikan** [comment]
I caught it. Bug.

**Comment by GuitarMan63** [comment]
@vomikan That's a result, I've just reinstalled 1.34 and that's all working as expected in terms of the filters, though I must admit I'd never spotted the ability to save the presets, live and learn. Keep up the good work, it's very much appreciated.

**Comment by MartinX3** [comment]
I can confirm it on Linux Arch MMEX v1.3.5
Downgraded DB from v14 to v7 and optimized after.

I use the advanced filter, the list blinks shortly and noting happened.

**Comment by MartinX3** [comment]
After a new release of mmex this ticket could be closed @GuitarMan63 .

**Comment by GuitarMan63** [comment]
Thanks MartinX3, Has the version changed and been uploaded?

I can still only see version 1.35, file size and date stamp look the same as the one I tried previously. I thought there might be a version 1.36 that had the bug fix. Once again many thanks for your assistance.

**Comment by MartinX3** [comment]
Dear @vomikan 
I sadly still face the same issue
![image](https://user-images.githubusercontent.com/4518092/103134384-1aefa200-46b1-11eb-98a6-38e11ddb0253.png)

**Comment by vomikan** [comment]
should be already fixed in 1.3.7
