### ISSUE TITLE
management of assets

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#4412]
MMEX version: - [x] 1.5.15 Beta2
Operating System: - [x] Windows
Is the bug reproducible?  - [x] Always 

by [mikeSK](https://forum.moneymanagerex.org/memberlist.php?mode=viewprofile&u=45396) » 19 May 2022 18:03
https://forum.moneymanagerex.org/viewtopic.php?p=22937#p22937

Why do asset accounts not roll up into total worth - according to the online help it does? So If I go into an asset account I can see the individual transactions but the summary of that account is always shown as zero and there is no breakdown of assets and/or value on the home screen. Do I need to change a setting or something?
-------------------------------------------------------------------------------------------
my answer:
there seems to be problems with the management of assets, I have done some tests and I can confirm this statement. if you add a position without opening an account first, MMEX even crashes.

**Comment by renato-mmex** [comment]
after step 4 MMEX dies:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/76920138/169570022-ac0fb8d4-f0d7-4a45-bd84-2153b9335e45.png">

**Comment by whalley** [comment]
Oddly, I can't reproduce this i=on either MacOS or Windows.

**Comment by renato-mmex** [comment]
have installed mmex-1.5.15-Beta.2-win64 on another Windows 11 Pro, also here MMEX dies after step 4

**Comment by PMaff** [comment]
Tried this for 
```
-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.15-Beta.3
-- Commit         : a3005d663 (2022-05-29)
-- Branch         : master
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 4.15.0-180-generic
-- Ubuntu 18.04 'bionic'
-- CMake 3.22.0
-- GNU Make 4.1
-- ccache 3.4.1
-- GNU 7.5.0
-- wxWidgets 3.1.5
-- wxSQLite3 4.6.0
-- Lua 5.3.3
-- curl 7.58.0
-- gettext 0.19.8.1

```

No crash on Ubuntu 18.04.
I get as step 5 the dialog "Add Asset Transaction" : 

![addasset](https://user-images.githubusercontent.com/93879362/170872722-83c796cd-8ce4-43b8-ac50-76c8f1977c43.jpg)

**Comment by whalley** [comment]
I still can't get it to crash. @renato-mmex Do you have a cut-down DB you can share that exhibits the crash.

**Comment by tactilis** [comment]
I get 1.5.15 Beta 3 on Win 7 to crash following Renato's 4 steps.

**Comment by tactilis** [comment]
You don't need a cut down database. It crashes from a minimal new database, as follows:

1. On the Startup page click Create a New Database. I called it AssetCrash.mmb
2. On the New Database Wizard click Next / Set Currency: GBP / Finish
3. On the Add Account Wizard click Cancel

Now follow Renato's steps:
1. Click Asset in the Nav tree
2. Click New button
3. On New Asset dialog: enter Name as A3, Value as 1, click OK.
3a. On the 'Asset account not found' message, click Yes.
4. On the Edit Account dialog, click OK

MMEX crashes

**Comment by whalley** [comment]
> You don't need a cut down database. It crashes from a minimal new database, as follows:
> ...
> MMEX crashes

Does not crash for me!


https://user-images.githubusercontent.com/487345/171043420-77944500-79b0-4983-adf3-d23243d4b562.mp4

**Comment by tactilis** [comment]
@whalley 
> Does not crash for me!

OK.

What, if anything, can I do to provide useful debugging info?  Is there a means of getting a stack trace or crash dump?

**Comment by vomikan** [comment]
I can reproduce it.

![image](https://user-images.githubusercontent.com/6836805/171053498-137ca132-7fb5-414b-b54c-7367fbbd419f.png)

**Comment by vomikan** [comment]
If you remove this line, the following transaction creation dialog appears. But when you click OK, a crash occurs again.
I can't understand the reason for this error.

**Comment by whalley** [comment]
It is an odd one that I can't seem to recreate on MacOS.

**Comment by PMaff** [comment]
@vomikan : just a short guess into the blue:
in the  same part of mmframe.cpp for 1.5.14 there was a default branch:
```
switch (Model_Account::type(account))
...
            default:
                tacct = m_nav_tree_ctrl->AppendItem(accounts, account.ACCOUNTNAME, selectedImage, selectedImage);
                break;
```
which is missing in 1.5.15-Beta.3

**Comment by vomikan** [comment]
There is a fix.

![image](https://user-images.githubusercontent.com/6836805/171150605-430b58fb-afb8-49f1-8e9e-11cf7699aa83.png)

**Comment by whalley** [comment]
Can't see any ill effect on MacOS of this change.

Guess this ticket still stands for the original query now the crash is resolved :-)

**Comment by tactilis** [comment]
Confirmed that the crash is now fixed on Windows.

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/3545

**Comment by PMaff** [comment]
> Confirmed that the crash is now fixed on Windows.

Still no crash on
```
Money Manager Ex
Version: 1.5.16 64-bit
• Build on Jun 25 2022 17:53:53
• Database version: 7 • (aes128cbc)
• Git commit: 9d7ca6e2b (2022-06-23)
MMEX is using the following support products:
• wxWidgets 3.1.5 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.4.4
• lunasvg v2.3.1
• libcurl/7.83.1 OpenSSL/1.1.1p-fips zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.47.0 OpenLDAP/2.6.2
• gettext 0.21
• apexcharts.js
Build using:
• CMake 3.23.2
• GNU Make 4.3
• GCC 12.1.0 • openSUSE 20220624
Running on:
• openSUSE Tumbleweed "n/a"
• Linux 5.18.6-1-default x86_64
• English (UTF-8)
• 0x0 0bit 96x96ppi
```

;-)

**Comment by n-stein** [comment]
Still crashing in 1.5.20 on Windows with the steps outlined above. Same issue as #4807 

https://github.com/moneymanagerex/moneymanagerex/blob/e30c87f4adff429e8fbf7a68fd36e0ff4df6ea1d/src/assetdialog.cpp#L436

**Comment by n-stein** [comment]
PR #5088 opened with fix

**Comment by whalley** [comment]
@vomikan Don't think this is closed. It is just the crash fix, not the original issue. That's my understanding anyway.

**Comment by n-stein** [comment]
@whalley I think you fixed this in #5111. The net worth at the top of the home screen includes assets and there is now an asset breakdown as well.

![image](https://user-images.githubusercontent.com/16599929/196719104-162e8f3c-1001-4ba3-90ad-52148ca55f54.png)

**Comment by whalley** [comment]
@n-stein Good point. Will close.
