### ISSUE TITLE
Monthly Budget showing wrong "Actual" totals

### ISSUE THREAD

**Issue by nachospada** [moneymanagerex/moneymanagerex#5137]
I noticed that the **_Actual_** column in the monthly budget shows a total that is way off. If I go check the report for that category the total is completely different to the **_Actual_** in the budget Setup. It was working perfectly fine before this new update.

**Comment by whalley** [comment]
Issue fixed in current v1.5.22Beta - https://github.com/moneymanagerex/moneymanagerex/issues/5106

The budget reports however should be correct.

You can try the beta build here: https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/44894486/job/8at7didfxla94409/artifacts

**Comment by nachospada** [comment]
Thank you for reply.

Unfortunately I use Mac so I can’t use this beta version. But I really appreciate the message. I’ll wait to the release.

Thank you again.
Nacho

**Comment by whalley** [comment]
Mac betas here: https://tinyurl.com/mmex-mac-betas

**Comment by nachospada** [comment]
Hi Mark, thank you for that. I downloaded it and installed but the issue is still there. In the budget the actual column total is off.

**Comment by whalley** [comment]
I trust you are using the latest beta 2022-09-28.

If so, can you please more information

1. When you say 'In the budget the actual column total is off', to which total are you referring?
<img width="762" alt="CleanShot 2022-09-28 at 10 55 50@2x" src="https://user-images.githubusercontent.com/487345/192749760-e8fa5378-6586-4ff5-b00f-7afd7529e04e.png">

Some example screenshots would be useful to illustrate the issue.

**Comment by nachospada** [comment]
The last column its header is _**Actual**_ ... that's the one. When I compare that column with the report total for that month the values are different

**Comment by nachospada** [comment]
This is the value in the budget
![Screen Shot 2022-09-28 at 6 00 58 PM](https://user-images.githubusercontent.com/44822250/192751049-b279b729-95e3-4dd1-b773-0bca8ca6807a.png)


And this is the total in the report (which is correct)
![Screen Shot 2022-09-28 at 6 01 31 PM](https://user-images.githubusercontent.com/44822250/192751205-412526fd-6b52-44ac-a21d-c1f2566ce760.png)

**Comment by whalley** [comment]
Do you just have Yearly/Monthly or Yearly and Monthly budgets?

What is this setting:
![CleanShot 2022-09-28 at 11 18 53@2x](https://user-images.githubusercontent.com/487345/192754882-c5cb06e3-3657-4a05-adb3-88796ea7072d.png)

You can see some discussion this here: https://github.com/moneymanagerex/moneymanagerex/issues/4214

**Comment by nachospada** [comment]
My settings are exactly like those… I have only the 3rd option checked

**Comment by whalley** [comment]
> My settings are exactly like those… I have only the 3rd option checked

Are you using yearly or monthly budgets or both?

**Comment by nachospada** [comment]
I have both setup

**Comment by nachospada** [comment]
![Screen Shot 2022-09-28 at 6 34 51 PM](https://user-images.githubusercontent.com/44822250/192757893-e9a8ee63-57c0-4852-aeb5-b8b6f723aaa4.png)

**Comment by whalley** [comment]
Think I've spotted the issue.
Can you try this build [mmex-1.5.22-Beta.1-Darwin-2022-09-28-2.dmg](https://1drv.ms/u/s!AkTX0ojXg_ughrwRKY4gzjo4Q8JSbg?e=5tURKC) and let me know if that rectifies the issue.

**Comment by nachospada** [comment]
Hey Mark, I installed that beta but unfortunately the bug still persists. 

Here's the budget
![Screen Shot 2022-09-29 at 7 16 17 AM](https://user-images.githubusercontent.com/44822250/192904929-939b8de7-3437-45ac-bfee-cf108ad61f3d.png)


And this is the report for the same month
![Screen Shot 2022-09-29 at 7 16 34 AM](https://user-images.githubusercontent.com/44822250/192904970-c1accf92-09e9-4fc5-b064-fb21b0b4c576.png)

**Comment by whalley** [comment]
Are there any TRANSFERS with the category Groceries, Merienda, and Restaurant ?

Think I'm probably going to need a database to debug this. Is it possible to take a copy of the database and cut it down such that the problem still exists. If so, can you mail it to support@moneymangerex.org

**Comment by whalley** [comment]
Just in case I'm missing anything. Here is the small test DB I've been using. Do you spot any issues in the budget reports?
[Budgets.zip](https://github.com/moneymanagerex/moneymanagerex/files/9672136/Budgets.zip)

**Comment by nachospada** [comment]
I just installed the version 1.5.18 and it works perfect. Now the actual column in the budget is showing exactly the same amount as the total for the month in the report.

**Comment by whalley** [comment]
> None... still the same problem.

You responded "None... still the same problem."  Which is it? "None" - you do not spot any issues, or "still the same problem" - You spot issues, in which case can you elaborate.

>  I hope it gets fixed in future releases. 

It won't as I have no idea what your problem is. Do the results in the example database I attached work? If not, tell me what is wrong. Can you replicate your issue by amended the sample database and reposting.

I previously asked when I posted the example database  "Do you spot any issues in the budget reports?"

**Comment by nachospada** [comment]
So in the test DB that you sent it doesn't look like there is any error. But when I load my db the error appears on the new release, but it doesn't show on the version 1.5.18 

Here is a screenshot of the budget on version 1.5.18
![Screen Shot 2022-10-04 at 11 10 23 AM](https://user-images.githubusercontent.com/44822250/193726292-cb728e1d-14f6-4a82-bca5-173cb546418d.png)


And this is the same screenshot on version 1.5.22
![192904929-939b8de7-3437-45ac-bfee-cf108ad61f3d](https://user-images.githubusercontent.com/44822250/193726400-ef0de97f-eb48-4939-bb89-4691235bdee7.png)


I can't tell you what's the issue because the db is exactly the same but as you can see the values are completely different. I'm not sure why though.

**Comment by nachospada** [comment]
Found it! Finally ... the _**Ignore Future Transactions**_ option needs to be checked even though those future transactions are not from the same month. I don't know why it's getting transactions to be paid on November when the budget is for the month of October. 

![Screen Shot 2022-10-04 at 11 16 54 AM](https://user-images.githubusercontent.com/44822250/193727135-5c734fe0-e375-48b1-a2aa-c875d643de1a.png)

**Comment by nachospada** [comment]
The problem now is that future transactions don't show anywhere. If I check that option it removes them from the budget and everywhere else

**Comment by whalley** [comment]
October has 30 days NOT 31, but you have nailed the issue. Thanks for preserving with this.

Have found the bug.

**Comment by whalley** [comment]
Latest Beta build with the fix available: https://moneymanagerex.org/docs/downloads/development/

**Comment by nachospada** [comment]
Cool. Happy to help ... I'm a developer too so I was trying to figure out what was causing that bug. Sorry for the delay on some of the answers. Cheers

**Comment by whalley** [comment]
If you can test and confirm it is fixed in the Beta that would be great. Oh, and close the issue if all OK.

**Comment by nachospada** [comment]
Yes I just installed the latest beta and now works as expected. Thank you. Closing the issue now. Cheers.
