### ISSUE TITLE
Opening New Transaction window for the first time, does not show date correctly

### ISSUE THREAD

**Issue by FlameHorizon** [moneymanagerex/moneymanagerex#5807]
MMEX version:
 - [x] 1.6.4-Beta.4
 
Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux 

# Description of the bug

Opening New Transaction window for the first time, does not show date correctly. Closing New Transaction window and opening it again shows date correctly.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Open MMEX
2. Go to account
3. Press new button to create a new transaction

Expected result:

Date should be displayed.

Actual result:

Control, which displays date is to small to show anything.

![Peek 2023-04-08 16-16](https://user-images.githubusercontent.com/23423558/230726041-fac80fa6-3e3b-463e-b62a-8b1609f23fe7.gif)

**Comment by n-stein** [comment]
Linux issue, likely due to #5668. Probably just need to set a minimum width for the field.

**Comment by n-stein** [comment]
I am unable to reproduce on Debian Bullseye.

**Comment by n-stein** [comment]
@FlameHorizon Which distro are you running? I'll spin up a VM and try to reproduce & debug using the same.

**Comment by n-stein** [comment]
@ovari Do you see this issue in Linux Mint?

**Comment by ovari** [comment]
@n-stein sorry, couldn't reproduce with Linux Mint.

**Comment by ovari** [comment]
@n-stein have experienced this bug now.

**Comment by GrahamLees** [comment]
This issue still exists in Flathub version 1.7.0 as of 12th March 2024 (Linux Debian 12.5).
The date is actually correct but displayed incorrectly in the field (System Language = English, Formats = France) and the date drop down shows the correct calendar Month and Year combination. When selected, the date is correctly entered in to the Date transaction field despite the incorrect look in the New Transaction Transaction Details window.

**Comment by vomikan** [comment]
> This issue still exists in Flathub version 1.7.0 as of 12th March 2024 (Linux Debian 12.5). The date is actually correct but displayed incorrectly in the field (System Language = English, Formats = France) and the date drop down shows the correct calendar Month and Year combination. When selected, the date is correctly entered in to the Date transaction field despite the incorrect look in the New Transaction Transaction Details window.

Could you, please, provide a screenshot?

**Comment by GrahamLees** [comment]
You might also like to see the settings:

![mmex date set](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/a6680ee2-0a8b-4a65-b327-53dd18bd6882)

**Comment by n-stein** [comment]
The format of the date controls in wxWidgets is locale based. In Windows it's entirely dependent on your system locale, but for Linux you can try changing the locale in the MMEX options (the blank drop-down below currency in your screenshot).

**Comment by GrahamLees** [comment]
"try changing the locale in the MMEX options"
Sadly, that didn't work. Changed it to "en_GB" with currency set as "British Pound" saved it but no change (even after re-launch). 
For completeness, I also tried changing it to fr_FR (same as formats in the system) but that wouldn't save out - error "Locale Invalid value".

**Comment by n-stein** [comment]
> For completeness, I also tried changing it to fr_FR (same as formats in the system) but that wouldn't save out - error \"Locale Invalid value\".

For Linux I you may need to also specify the encoding. Try adding ".UTF-8" as in 

en_GB.UTF-8
fr_FR.UTF-8

You can type in the locale box directly.

**Comment by GrahamLees** [comment]
> en_GB.UTF-8
fr_FR.UTF-8

Tried that and no change sadly. 
"en_GB.UTF-8 was allowed but didn't change the date format in the New Transaction dialogue and "fr_FR.UTF-8 was refused with the same error as before.

**Comment by n-stein** [comment]
I just tested this on my system. Changing MMEX's locale setting did not work, but setting a different system locale did change the display of the date.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/62e7f0a4-5724-4271-84dd-d80af1f8ce0a)

What is the output of the commands `locale` and `locale -a` on your system?

**Comment by GrahamLees** [comment]
That's bizarre - it certainly doesn't work that way on my instance. I tried different locales but the always errored out. 
Here's a screenshot of the `locale`command
 ![locale](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/cdf9d824-0244-454a-a71c-d96a582d751c)

**Comment by n-stein** [comment]
Ah, you are using mixed locales. What is the output of `flatpak info org.gnome.Platform.Locale`? Do you see both languages listed at the bottom?

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/ca9008c7-ae34-4036-a314-c3ac13670e75)


In the past Flatpak has had issues when the system locales use multiple languages. See https://github.com/flatpak/flatpak/issues/3712.

Maybe try:

```
flatpak --user config --set languages 'en;fr'
flatpak update
```

**Comment by n-stein** [comment]
@ovari is the original issue here (date field too small) still a problem for you in the 1.7.1 beta?

**Comment by GrahamLees** [comment]
Seems only /en for Flatpak but France formats are available - I installed them as they are not there by default on Debian. `sudo dpkg-reconfigure locales` and then add `fr_FR.UTF-8 UTF-8`
![Flatpak_platform](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/e7c0878c-5ca3-44e9-95ac-b4f4740eb307)

This shows the Settings for Language and Region after `sudo dpkg-reconfigure` was used:
![Debian Region](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/d5d0b239-5dc0-49a0-9499-9dd273865522)

**Comment by n-stein** [comment]
> Seems only /en for Flatpak but France formats are available - I installed them as they are not there by default on Debian.

Since they are available on the OS you should be able to add them to flatpak. Try:

`flatpak update --subpath=en,fr org.gnome.Platform.Locale`

**Comment by GrahamLees** [comment]
Appreciate your help on this issue but I'm curious to know how this might affect things generally since selecting the UK format had no effect on the date field and other Flatpaks seem unconcerned that the locale is not present in the `gnome.Platform.Locale` file when selecting `Help  > About`

**Comment by n-stein** [comment]
> Appreciate your help on this issue but I'm curious to know how this might affect things generally since selecting the UK format had no effect on the date field and other Flatpaks seem unconcerned that the locale is not present in the `gnome.Platform.Locale` file when selecting `Help → About`

Sorry, I don't know enough about Flatpak to be informative here. Perhaps @joshua-stone has some insight?

**Comment by ovari** [comment]
> @ovari is the original issue here (date field too small) still a problem for you in the 1.7.1 beta?

Have seen this behavior before; however, have not seen this issue recently. Sorry, don't know how to reproduce.

```
$ flatpak info org.gnome.Platform.Locale
error: Multiple branches available for org.gnome.Platform.Locale, you must specify one of: org.gnome.Platform.Locale/x86_64/44, org.gnome.Platform.Locale/x86_64/45
```

```
Money Manager Ex
• Version: 1.7.1-Beta.1 64-bit
• Built on: Mar 12 2024 03:16:33
• Database version: 19 (aes128cbc)
• Git commit: 0e99b4c2e (2024-03-11)
• Git branch: master
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxGTK 3.24)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV OpenSSL/3.1.5 zlib/1.3.1 nghttp2/1.58.0
• gettext 0.22
• apexcharts.js
Built with:
• CMake 3.28.3
• GNU Make 4.4.1
• GCC 13.2.0
Running on:
• GNOME.45 (Flatpak runtime)
• GNOME 45 (Flatpak runtime) ""
• Linux 5.15.0-100-generic x86_64
• X-Cinnamon (X11)
• System Locale: en_AU.UTF-8
• User Interface Language: en_US.UTF-8
• 1368x768 24-bit 96x96ppi
```

**Comment by GrahamLees** [comment]
@ovari 
> Sorry, don't know how to reproduce.

Did that refer to the issue about locale I raised in respect of incorrect date format?
If so, thinking about it, this was a fresh installation of Debian 12.5 and ISTR that I installed Flatpak and then MMEX _before_ I configured locales using `sudo dpkg-reconfigure locales` which cold be the way to reproduce the issue.
Kind regards.

**Comment by ovari** [comment]
> Did that refer to the issue about locale I raised in respect of incorrect date format? If so, thinking about it, this was a fresh installation of Debian 12.5 and ISTR that I installed Flatpak and then MMEX _before_ I configured locales using `sudo dpkg-reconfigure locales` which cold be the way to reproduce the issue. Kind regards.

Where are in you installing the Flatpak from:
1. Stable version 1.7.0 from Flathub: https://flathub.org/apps/org.moneymanagerex.MMEX
2. Development version 1.7.1-Beta.1: https://github.com/moneymanagerex/moneymanagerex/issues/6246#issuecomment-1771746959

**Comment by ovari** [comment]
> Seems only /en for Flatpak but France formats are available - I installed them as they are not there by default on Debian. `sudo dpkg-reconfigure locales` and then add `fr_FR.UTF-8 UTF-8` ![Flatpak_platform](https://private-user-images.githubusercontent.com/65292770/312500215-e7c0878c-5ca3-44e9-95ac-b4f4740eb307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTg2NjcsIm5iZiI6MTcxMDM5ODM2NywicGF0aCI6Ii82NTI5Mjc3MC8zMTI1MDAyMTUtZTdjMDg3OGMtNWNhMy00NGU5LTk1YWMtYjRmNDc0MGViMzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA2MzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMjc0Zjc0MmU5Mzg4MWI5M2U2ODVlZTdiNjE2NzQ2ZjU1NTQ5ZTJiNTgwYTQ0NDc3NjVkMDkzNjRhZDQwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T2S9KKNcsR2iUz1iDHIUM_5LJKW20xrjlRp5qDlUzWI)

@GrahamLees your screenshot shows version 44, not version 45, of the GNOME platform. Are you using the latest, i.e. beta, version of MMEX? If not, can you please test with the MMEX development version 1.7.1-Beta.1?

Instructions to install the latest MMEX development version can be found here: https://github.com/moneymanagerex/moneymanagerex/issues/6246#issuecomment-1771746959

Thank you

**Comment by GrahamLees** [comment]
The version of GNOME is actually 43.9

![image](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/c85b2c98-710e-4ac4-b4cb-33348628968e)

MMEX was installed from the standard repo using `GNOME Software`. 
I have been a long time user of MMEX. The data for this version (on Debian) was exported in a `.qif` file from version 1.4.0-alpha on my Ubuntu 22.04 instance if that helps.
I'll have a look at installing the development version but as the current instance 1.7.0 contains live data I'm keen not to lose it.

**Comment by ovari** [comment]
> I'll have a look at installing the development version but as the current instance 1.7.0 contains live data I'm keen not to lose it.

Can you please check with the 1.7.1 development version as it is understood that this issue was present in version 1.7.0 and has been resolved sometime during the 1.7.1 development cycle?

**Comment by GrahamLees** [comment]
I'll have a go at installing 1.7.1 later after protecting my data and then get back to you.

**Comment by GrahamLees** [comment]
@ovari well I tried following those instructions but couldn't get it to finish. I got as far as step 7 and saved the file to:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/b41ee4f3-c9d0-4639-8420-e062c7172120)
Navigated my way to the directory in terminal and issued the command as shown with the following result:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/e7c37fc9-61cd-420f-adaa-4ebf68314a40)
I'll just reinstall the Flatpak from the repo as before and wait until the development version is committed and update from there. The issue is no big deal to be honest, The date picker calendar confirms the date is correct in the field - just presented wrongly - and the date entered in the transaction field is correct in every respect.

**Comment by ovari** [comment]
The location where the mmex.flatpak file was downloaded is a temporary location and does not allow full permissions. Also, once you close the browser, the downloaded files may be deleted.

Copy the mmex.flatpak file to your Downloads directory (or Desktop). Somewhere that the file will be available after you close the browser and also have permissions to run the file.

**Comment by GrahamLees** [comment]
ah, understood. I wondered if I should change the download directory doh 🙄
However, there is no change. I navigated to the directory I created in Downloads and ran it, it opened but the same version number is shown and the original error remains. I confirmed this with `flatpak list mmex` .
listing my flatpaks I seem to have 2 entries:
`MMEX Money Manager org.moneymanagerex.MMEX        1.7.1 Beta 1 master      mmex-origin system`

`MMEX Money Manager org.moneymanagerex.MMEX        1.7.0        stable      flathub     system` 

The only one that loads is the old version which I removed from from the GNOME software list of installed packages but is seems to remain? I seem unable to run the beta version.
Advice? 
Sorry to be a pain.

**Comment by ovari** [comment]
Perhaps https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-run can provide some help?

1. Open the Terminal
2. Type the following and press `Enter`
```
$ flatpak run --branch=master org.moneymanagerex.MMEX
```

Does that work to run the master branch (i.e. 1.7.1 Beta 1)?

**Comment by GrahamLees** [comment]
> Does that work to run the master branch (i.e. 1.7.1 Beta 1)?

No, it stil wants to open the 1.7 version and errors with `Warning: Cannot set locale to language ""`

There are still 2 versions listed in `flatpak list`. Going to delete from GNOME software again and have another look at it.

**Comment by GrahamLees** [comment]
OK, so now I only have the beta version listed:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/b8c71b66-1b3e-4634-9b00-31a74e8e9b01)
However, it still says `Cannot set locale to language ` when running the command:
`flatpak run --branch=master org.moneymanagerex.MMEX`
It shows that I am running the correct version:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/ae446aad-c03d-431a-8103-7a3b67b749d7)
However, we are no further forward.
When opening the app and selecting the existing database :
![image](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/3508358d-744f-42d7-a0af-cf372c99cfb6)
and -
![image](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/8550812c-0c90-4ee5-8a04-539faa7bd4e2)
The date is still shown as before 🙄
Don't know where else I can go with this now other than just accept that the bug still exists and ignore it.

**Comment by ovari** [comment]
> When opening the app and selecting the existing database :
> ![image](https://private-user-images.githubusercontent.com/65292770/313166907-3508358d-744f-42d7-a0af-cf372c99cfb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDEyNzcsIm5iZiI6MTcxMDUwMDk3NywicGF0aCI6Ii82NTI5Mjc3MC8zMTMxNjY5MDctMzUwODM1OGQtNzQ0Zi00MmQ3LWEwYWYtY2YzNzJjOTljZmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDExMDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MjhiNWQ4MDllZTE1ODEyMzkzYTljMWYwYTc4NzI0Mjc2YzhiYWYwNzhjYTFjZWRmNmY1ZGZiYTQwOWUzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2vFcnc59s6hsek7j5rkFcl7AVRwRwUasiwOmWtyERLs)

https://askubuntu.com/questions/1406523/some-flatpak-apps-do-not-display-the-right-locale-language-on-ubuntu-22-04
https://github.com/flathub/org.gnome.Rhythmbox3/issues/53
https://github.com/flathub/org.gnome.Rhythmbox3/pull/52

Does typing the following in your Terminal help:
```
flatpak run --env=LC_MESSAGES=fr_FR.UTF-8 org.moneymanagerex.MMEX
```

**Comment by ovari** [comment]
What flatpak version do you have on your computer?

```
$ flatpak --version
Flatpak 1.12.7
```

**Comment by GrahamLees** [comment]
@ovari  1.14.4

**Comment by GrahamLees** [comment]
@ovari I just tried creating a new database in a separate directory (so not using the existing data set) and this is the same result:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/76625bf5-dfb9-4ad6-b78e-07104cd09e55)
Perhaps we can now safely say that this is not working correctly on Debian 12?

**Comment by GrahamLees** [comment]
@ovari By the way - just for completeness, I did use `flatpak update --subpath=en,fr org.gnome.Platform.Locale` suggestion and it made no difference to the issue.

**Comment by n-stein** [comment]
> Ialso ran `flatpak run --env=LC_MESSAGES=fr_FR.UTF-8 org.moneymanagerex.MMEX` as you mentioned earlier with the result `Warning: Cannot set locale to language ""`

LC_MESSAGES changes the UI language. You want to run `flatpak run --env=LC_TIME=fr_FR.UTF-8 org.moneymanagerex.MMEX` to change the date setting.

**Comment by GrahamLees** [comment]
@n-stein Yes! that did the trick - thank you so much 🙂
![image](https://github.com/moneymanagerex/moneymanagerex/assets/65292770/7fdfeec7-d33b-4619-a0be-8f8eae3183ff)

**Comment by GrahamLees** [comment]
I abandoned using this app some time ago and now have no further interest in it but with many thanks to those who contributed to the question.
