### ISSUE TITLE
Hidden columns in account view still display their values over active columns

### ISSUE THREAD

**Issue by MartinX3** [moneymanagerex/moneymanagerex#749]
Refrence to this bug.
[https://sourceforge.net/p/moneymanagerex/bugs/809/](https://sourceforge.net/p/moneymanagerex/bugs/809/)
[https://sourceforge.net/p/moneymanagerex/bugs/809/attachment/display-bug.png](https://sourceforge.net/p/moneymanagerex/bugs/809/attachment/display-bug.png)

You can't enable the ID-Column.
Disabled Columns doesn't disappear.
Only the Column Header disappear, not the column value in each row.

**Comment by dwrj87** [comment]
#491

**Comment by vomikan** [comment]
I don't beleave that you can't  enable the ID-Column.
There is right click menu should be available on colunms header.

**Comment by MartinX3** [comment]
Yes, there is.
But i can't make a tick at the ID-Column-Option.

**Comment by vomikan** [comment]
Ha. The same issue on Windows PC. Seems becouse the ID column default size is 0.
Try to drag the right size of the first column.

**Comment by MartinX3** [comment]
I can't make the column large
if i try to drag the side of the first colum or the second (date) column, i slide only the size of the colum with the date or the column with the tick.
And if i try to enable the ID-Column in the right click menu, there wont be a tick, which would show me, that the column got activated.

**Comment by MartinX3** [comment]
Thank you for the fix!
In which Version will it be?
1.2.6-trusty1 is not fixed.
I want to test it.

**Comment by vomikan** [comment]
The developer way is build mmex from  scratch https://sourceforge.net/p/moneymanagerex/wiki/Building%20mmex%20Debian%20%28Ubuntu%29%20Linux/
It will help to check if the problem gone before relese.

Another options is waiting 1.2.7 release. But no garanty that my changes fix the problem. I've fixed only the I'D column sizing.

**Comment by MartinX3** [comment]
Linux Mint 18.1.
Based on Ubuntu 16.04.
64-Bit & Mate-Desktop.
PPA-Version 1.2.7.

I can deactivate the ID colum header.
but the visual bug (like #491) still happens.

![bildschirmfoto zu 2016-12-26_12-58-56](https://cloud.githubusercontent.com/assets/4518092/21481696/229313c2-cb6b-11e6-8391-ec7faa7eb329.png)

**Comment by vomikan** [comment]
Is this issue actual for mmex 1.3.0 ?

**Comment by MartinX3** [comment]
I only can test it, when the Linux PPA is updated from 1.2.7 to 1.3.0 :(

**Comment by vomikan** [comment]
May be you can build mmex from scratch?
https://sourceforge.net/p/moneymanagerex/wiki/Building%20mmex%20Debian%20%28Ubuntu%29%20Linux/

**Comment by BentleyJOakes** [comment]
This issue is still present in master when building from scratch.

**Comment by MartinX3** [comment]
SAME ERROR IN v1.3.1!
Fresh compiled from Github!

**Comment by slodki** [comment]
Please change issue title to "Hidden columns in account view still display their values over active columns".

`Hide/Show Column` hides only column header and makes column width 0, but hidden column values are still rendered over values of right side column. Bug is not related to ID/date only, multiple columns may be stacked over too

3 columns (status flag, ID and date) displayed as one:

![hidden column](https://cloud.githubusercontent.com/assets/3155552/25775412/fadaf60a-32a4-11e7-9930-53678e482dc1.png)

All columns active:
![hidden1](https://cloud.githubusercontent.com/assets/3155552/25775484/2defcab0-32a6-11e7-9c10-d3127a839669.png)
After hide `Withdrawal` column (hidden column value changes formatting: it is left aligned and without decimal places):
![hidden2](https://cloud.githubusercontent.com/assets/3155552/25775490/3a7a6f74-32a6-11e7-8fd1-7af62750de73.png)

**Comment by vomikan** [comment]
@slodki  thank you for your explanation of a root issue of the problem.

**Comment by slodki** [comment]
wxWidgets [#17922](https://trac.wxwidgets.org/ticket/17922) reported

**Comment by slodki** [comment]
wxWidgets team reports this issue ([#17922](https://trac.wxwidgets.org/ticket/17922#comment:1)) should be fixed now at master and WX_3_0_BRANCH.
We can retest this using development version of wxWidgtes...

**Comment by slodki** [comment]
This is fixed in latest wxgtk versions (both 3.1.1 and 3.0.4). MMEX build with new wxgtk are ok. Tested with latest Ubuntu Artful build.
